[theme]
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#FFFFFF"
separator = "  "

[icons]
[icons.overrides]
volume = [ "Volume:" ]
volume_muted = [ "Muted:" ]

[[block]]
block = "sound"
max_vol = 100
show_volume_when_muted = true

[[block]]
block = "battery"
interval = 60
charging_format = " Charging: $percentage "
not_charging_format = " Capacity: $percentage "
empty_format = " Capacity: $percentage "
full_format = " Capacity: $percentage "
format = " Capacity: $percentage "

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%Y.%-m.%-d %-H:%M')"