(add-hook 'activate-mark-hook '(lambda () 
                             (set-face-attribute 'mode-line nil :height 1.0)
                             ))
(add-hook 'after-change-major-mode-hook '(lambda () 
                                           (highlight-parentheses-mode)
                                           ))
(add-hook 'deactivate-mark-hook '(lambda () 
                             (set-face-attribute 'mode-line nil :height 5)))
(add-hook 'ess-mode-hook '(lambda () 
                            (hs-org/minor-mode t)
                         ;   (hs-hide-all)
                            (whitespace-mode)
                            (pretty-symbols-mode)
                            ))
(add-hook 'find-file-hook '(lambda ()
                       (hs-hide-all)
                       ))
(add-hook 'first-change-hook '(lambda () (setq-local knu/modified t)))
(add-hook 'LilyPond-mode-hook '(lambda () 
                                 (hs-org/minor-mode t)
                                 (highlight-parentheses-mode)
                                 (whitespace-mode)
                                 ))
(add-hook 'minibuffer-setup-hook '(lambda () 
                             (set-face-attribute 'mode-line nil :height 1.0)))
(add-hook 'minibuffer-exit-hook '(lambda () 
                            (set-face-attribute 'mode-line nil :height 5)))
(add-hook 'org-after-todo-statistics-hook 'org-summary-todo)
(add-hook 'org-mode-hook '(lambda ()
                            (flyspell-mode)
                            (define-key org-mode-map (kbd "C-c C-x a") 'knu/org-archive)
                            ))
(add-hook 'post-command-hook 'hcz-set-cursor-color-according-to-mode)
(add-hook 'prog-mode-hook '(lambda () 
                             (hs-org/minor-mode t)
                             (pretty-symbols-mode)
                             ))
(add-hook 'python-mode-hook '(lambda ()
                               (whitespace-mode)
                               ))
(add-hook 'text-mode-hook 'pretty-symbols-mode)
(add-hook 'w3m-mode-hook '(lambda ()
                            (load "w3m-config.el")
                            ))

