(add-hook 'kill-emacs-hook '(lambda () (when (fboundp 'gnus-group-exit) (defun gnus-y-or-n-p (yes) yes)
                              (gnus-group-exit))))
(add-hook 'after-change-major-mode-hook '(lambda () 
                                           (highlight-parentheses-mode)
                                           ))
(add-hook 'ess-mode-hook '(lambda () 
                            (whitespace-mode)
                            (pretty-symbols-mode)
                            ))
(add-hook 'LilyPond-mode-hook '(lambda () 
                                 (highlight-parentheses-mode)
                                 (whitespace-mode)
                                 ))
(add-hook 'org-after-todo-statistics-hook 'org-summary-todo)
(add-hook 'org-mode-hook '(lambda ()
                            (flyspell-mode)
                            (define-key org-mode-map (kbd "C-c C-x a") 'knu/org-archive)
                            ))
(add-hook 'post-command-hook 'hcz-set-cursor-color-according-to-mode)


(add-hook 'prog-mode-hook '(lambda ()
                             (when (not  (or (equal major-mode 'emacs-lisp-mode)
                                          (equal major-mode 'lisp-interaction-mode))) (whitespace-mode))
                             ))
(add-hook 'text-mode-hook 'pretty-symbols-mode)
(add-hook 'w3m-mode-hook '(lambda ()
                            (load "w3m-config.el")
                            ))
