(setq knu-org-mode-map t)

(define-key org-mode-map "α" "\\alpha")
(define-key org-mode-map "β" "\\beta")
(define-key org-mode-map "γ" "\\gamma")
(define-key org-mode-map "δ" "\\delta")
(define-key org-mode-map "ε" "\\epsilon")
(define-key org-mode-map "ζ" "\\zeta")
(define-key org-mode-map "θ" "\\theta")
(define-key org-mode-map "ι" "\\iota")
(define-key org-mode-map "κ" "\\kappa")
(define-key org-mode-map "λ" "\\lambda")
(define-key org-mode-map "μ" "\\mu")
(define-key org-mode-map "ν" "\\nu")
(define-key org-mode-map "ξ" "\\xi")
(define-key org-mode-map "ο" "\\omicron")
(define-key org-mode-map "π" "\\pi")
(define-key org-mode-map "ρ" "\\rho")
(define-key org-mode-map "σ" "\\sigma")
(define-key org-mode-map "τ" "\\tau")
(define-key org-mode-map "φ" "\\phi")
(define-key org-mode-map "χ" "\\chi")
(define-key org-mode-map "ψ" "\\psi")
(define-key org-mode-map "ω" "\\omega")

